### ISSUE TITLE
Is this really a few-shot work?

### ISSUE THREAD

**Issue by Lizhuoling** [brjathu/SKD#1]
Hi, I have read the paper and source code. In this work, the input of the model contains several images and the output is the predicted categories. The size of the output seems to be fixed. It does not work in some common few-shot styles, such as metric learning and matching network form. In this way, How could the model deal with objects of new categories? To my sense, the proposed method seems working in a fully-supervised classification setting rather than the few-shot classification setting.

**Comment by brjathu** [comment]
The fixed final layer is used for pretraining, once it’s pretrained any new classes can be used in few shot manner, since the few shot classification happens as logistic regression on the feature embeddings. See 3.4 evaluation section in the paper.
